domain: "###ZARF_VAR_DOMAIN###"

renovate:
  logLevel: "debug"
  printconfig: "true"
  platform: "gitlab"
  endpoint: "https://gitlab.###ZARF_VAR_DOMAIN###/api/v4" #todo substitute domain here
  autodiscover: "true"
  onboarding: "true"

  # Additional environment variables for Renovate (see: https://docs.renovatebot.com/self-hosted-configuration/)
  extraEnv: {}

  gitlabToken:
    # value will be used directly if given, else the value will be looked up from existing secret as specified in fromExistingSecret
    #value: ""
    fromExistingSecret:
      name: gitlab-token-renovate
      namespace: gitlab
      tokenKey: TOKEN
