domain: "###ZARF_VAR_DOMAIN###"

renovate:
  logLevel: "info"
  printconfig: "true"
  platform: "gitlab"
  endpoint: "https://gitlab.uds.dev/api/v4" #todo substitute domain here
  autodiscover: "true"
  onboarding: "false" #todo default to on

  # Additional environment variables for Renovate (see: https://docs.renovatebot.com/self-hosted-configuration/)
  extraEnv: {}

  gitlabToken:
    # value will be used directly if given, else the value will be looked up from existing secret as specified in fromExistingSecret
    #value: ""
    fromExistingSecret:
      name: gitlab-token-renovate
      namespace: gitlab
      tokenKey: TOKEN
