domain: "###ZARF_VAR_DOMAIN###"

gitlab:
  existingSecret:
    name: gitlab-token-root
    namespace: gitlab
    tokenKey: TOKEN

# Additional environment variables for Renovate
extraEnv:
  LOG_LEVEL: "debug"
  RENOVATE_PLATFORM: "gitlab"
  RENOVATE_ENDPOINT: "https://gitlab.uds.dev/api/v4"
  RENOVATE_AUTODISCOVER: "true"
  RENOVATE_DRYRUN: "false"
  RENOVATE_PRINTCONFIG: "true"
  RENOVATE_ONBOARDING: "false"
