domain: "###ZARF_VAR_DOMAIN###"

redis:
  enabled: true # set to false to disable redis and store cache on local filesystem

  internal: true
  selector:
    app.kubernetes.io/name: valkey
  namespace: valkey-renovate

  host: "valkey-master.valkey-renovate.svc.cluster.local"
  port: 6379
  username: ""
  # Note: Specifying password as anything other than "" will not use the existingSecret
  password: ""
  existingSecret:
    name: valkey-password
    passwordKey: password

# token to use to communicate with the configured platform. (e.g PAT token for gitlab)
platformToken:
  # Note: Specifying value as anything other than "" will not use the existingSecret
  value: ""
  existingSecret:
    name: gitlab-token-renovate
    tokenKey: TOKEN

renovate:
  logLevel: "debug"
  printconfig: "true"
  platform: "gitlab"
  endpoint: "https://gitlab.###ZARF_VAR_DOMAIN###/api/v4"
  autodiscover: "true"
  onboarding: "true"

  # Additional environment variables for Renovate. Use this if you need to configure things
  # that aren't directly exposed by the uds-renovate-config chart. (see: https://docs.renovatebot.com/self-hosted-configuration/)
  extraEnv: {}

  config: |
    {
        "enabled": true,
        "forkProcessing": "enabled",
        "$schema": "https://docs.renovatebot.com/renovate-schema.json",
        "extends": [
            ":dependencyDashboard",
            "config:base",
            "helpers:pinGitHubActionDigests",
        ],
    }
