renovate:
  # This is a small starter config.json, the environment variables from renovate-env will get combined with this
  config: |
    {
      "printConfig": true
    }

cronjob:
  schedule: "###ZARF_VAR_RENOVATE_SCHEDULE###"

envFrom:
  - secretRef:
      name: renovate-env

serviceAccount:
  create: true
  annotations: {}
