renovate:
  # TODO (@EWYLES) -- just putting something here for now, need to figure out real config
  config: |
    {
      "printConfig": true
    }

# cronjob:
#   schedule: "0 * * * *"

envFrom:
  - secretRef:
      name: renovate-gitlab-token
  - secretRef:
      name: renovate-env

serviceAccount:
  create: true
  annotations: {}
