# Copyright 2024 Defense Unicorns
# SPDX-License-Identifier: AGPL-3.0-or-later OR LicenseRef-Defense-Unicorns-Commercial

image:
  registry: ghcr.io
  repository: renovatebot/renovate
  tag: 41.28.2-full
