apiVersion: v1
kind: Secret
metadata:
  name: renovate-env
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  RENOVATE_TOKEN: {{- if .Values.platformToken.value }}
    {{ .Values.platformToken.value | quote }}
  {{- else if .Values.platformToken.existingSecret.name }}
    {{- $secret := lookup "v1" "Secret" .Release.Namespace .Values.platformToken.existingSecret.name -}}
    {{- if $secret }}
      {{ $token := index $secret.data "TOKEN" | b64dec | quote }}
      {{ $token }}
    {{- end }}
  {{- end }}
  LOG_LEVEL: {{ .Values.renovate.logLevel | quote }}
  RENOVATE_ONBOARDING: {{ .Values.renovate.onboarding | quote }}
  RENOVATE_PLATFORM: {{ .Values.renovate.platform | quote }}
  RENOVATE_ENDPOINT: {{ .Values.renovate.endpoint | quote }}
  RENOVATE_AUTODISCOVER: {{ .Values.renovate.autodiscover | quote }}
  RENOVATE_PRINTCONFIG: {{ .Values.renovate.printconfig | quote }}
  {{- if .Values.redis.enabled }}
  RENOVATE_REDIS_URL: |-
    {{- $secret := "" }}
    {{- if and .Values.redis.existingSecret.name (eq .Values.redis.password "") }}
    {{- $secret = (lookup "v1" "Secret" .Release.Namespace .Values.redis.existingSecret.name) }}
    {{- end }}
    {{- if $secret }}
    {{- $password := index $secret.data .Values.redis.existingSecret.passwordKey | b64dec }}
    {{ .Values.redis.scheme }}://{{ .Values.redis.username }}:{{ $password }}@{{ .Values.redis.host }}:{{ .Values.redis.port }}
    {{- else }}
    {{ .Values.redis.scheme }}://{{ .Values.redis.username }}:{{ .Values.redis.password }}@{{ .Values.redis.host }}:{{ .Values.redis.port }}
    {{- end }}
  {{- end }}
{{- with .Values.renovate.extraEnv }}
{{- toYaml . | nindent 2 }}
{{- end }}
