apiVersion: v1
kind: Secret
metadata:
  name: renovate-env
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  RENOVATE_TOKEN: {{- if .Values.renovate.gitlabToken.value }}
    {{ .Values.renovate.gitlabToken.value | quote }}
  {{- else if .Values.renovate.gitlabToken.fromExistingSecret.name }}
    {{- $secret := lookup "v1" "Secret" .Values.renovate.gitlabToken.fromExistingSecret.namespace .Values.renovate.gitlabToken.fromExistingSecret.name -}}
    {{- if $secret }}
      {{ $token := index $secret.data "TOKEN" | b64dec | quote }}
      {{ $token }}
    {{- end }}
  {{- end }}
  LOG_LEVEL: {{ .Values.renovate.logLevel | quote }}
  RENOVATE_ONBOARDING: {{ .Values.renovate.onboarding | quote }}
  RENOVATE_PLATFORM: {{ .Values.renovate.platform | quote }}
  RENOVATE_ENDPOINT: {{ .Values.renovate.endpoint | quote }}
  RENOVATE_AUTODISCOVER: {{ .Values.renovate.autodiscover | quote }}
  RENOVATE_PRINTCONFIG: {{ .Values.renovate.printconfig | quote }}
{{- with .Values.renovate.extraEnv }}
{{- toYaml . | nindent 2 }}
{{- end }}
