apiVersion: v1
kind: Secret
metadata:
  name: renovate-gitlab-token
  namespace:  {{ .Release.Namespace }}
type: "Opaque"
stringData:
  RENOVATE_TOKEN: {{- if .Values.gitlab.existingSecret.name }}
    {{- $secret := lookup "v1" "Secret" .Values.gitlab.existingSecret.namespace .Values.gitlab.existingSecret.name -}}
    {{- if $secret }}
      {{ $token := index $secret.data "TOKEN" | b64dec }}
      {{ $token }}
    {{- else }}
      "undefined"
    {{- end }}
  {{- else }}
    "undefined"
  {{- end }}
