tasks:
  - name: create
    description: Create the Dependency Zarf Package
    actions:
      - cmd: uds zarf package create . --confirm --no-progress --architecture=${UDS_ARCH}
        dir: src/namespace
  - name: deploy
    description: Deploy the latest version of the dev GitLab bundle to use with the runner in tests
    actions:
      - description: Get latest tag version from OCI
        cmd: curl -s https://api.github.com/repos/defenseunicorns/uds-package-gitlab/tags  | yq -p=json -r '.[0].name'
        setVariables:
          - name: LATEST_VERSION
      - description: Pull the latest package release
        cmd: UDS_CONFIG=uds-config-gitlab.yaml uds deploy oci://ghcr.io/defenseunicorns/packages/uds/bundles/gitlab-test:$(echo ${LATEST_VERSION} | tr -d v) --confirm --no-progress
