# Copyright 2024 Defense Unicorns
# SPDX-License-Identifier: AGPL-3.0-or-later OR LicenseRef-Defense-Unicorns-Commercial

tasks:
  - name: deploy
    description: Deploy the latest version of the dev GitLab bundle to use with the runner in tests
    actions:
      - description: Get latest tag version from OCI
        cmd: curl -s https://api.github.com/repos/defenseunicorns/uds-package-gitlab/releases | uds zarf tools yq -p=json -r '.[].tag_name' | grep upstream | tail -n1
        setVariables:
          - name: LATEST_VERSION
      - description: Pull the latest package release
        cmd: UDS_CONFIG=uds-config-gitlab.yaml uds deploy oci://ghcr.io/defenseunicorns/packages/uds/bundles/gitlab-test:"$(echo "${LATEST_VERSION}" | sed 's/-upstream$//')" --confirm --no-progress
