tasks:
  - name: all
    actions:
      - task: cronjob

  - name: cronjob
    actions:
      - description: "execute job from cronjob"
      - cmd: uds zarf tools kubectl create job --from=cronjob/renovate renovate-manual-run -n renovate
