# Copyright 2024 Defense Unicorns
# SPDX-License-Identifier: AGPL-3.0-or-later OR LicenseRef-Defense-Unicorns-Commercial

name: PR Title Check

on:
  pull_request:
    branches: [main]
    types: [milestoned, opened, edited, synchronize]

# Permissions for the GITHUB_TOKEN used by the workflow.
permissions:
  contents: read # Allows reading the content of the repository.
  pull-requests: read # Allows reading pull requests

jobs:
  validate:
    uses: defenseunicorns/uds-common/.github/workflows/callable-commitlint.yaml@22be0673a01c1b8b00a0c9a3eb00f1bd618963a3 # v1.6.3
